<?php
/**
 * Created by PhpStorm.
 * User: elliot
 * Date: 14/09/2018
 * Time: 11:19
 */

namespace App\Controller;


use Cake\Controller\Controller;

class IndexController extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->loadComponent('ProtoWechat');
    }

    public function index(){
        $this->ProtoWechat->checkSignature();
    }

}
