<?php
/**
 * Created by PhpStorm.
 * User: elliot
 * Date: 13/09/2018
 * Time: 00:14
 */

namespace App\Controller\Component;


use Cake\Controller\Component;
use Cake\Core\Configure;
use EasyWeChat\Foundation\Application;

class MyWechatComponent  extends Component
{
    private $application;
    private $wxConfig;
    public function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub

        $this->wxConfig = Configure::read('wx_config');
        $this->application = new Application($this->wxConfig);
    }

    public function index(){
        $app= $this->application;
        $server = $app->server;

        $server->setMessageHandler(function ($message){
            if ($message->MsgType == 'event'){
                switch ($message->Event){
                    case 'subscribe':         // 关注事件
                        return "欢迎关注我！";
                        break;
                    case 'unsubscribe':       // 取消关注
                        break;
                    default:
                        break;
                }
            } else {
                switch ($message->MsgType){
                    case 'text':    // 文本消息
                        switch ($message->Content){
                            case 'info':
                                return 'hello';
                                break;
                        }
                        break;
                    case 'image':   // 图片消息
                        break;
                    case 'voice':   // 语音消息
                        break;
                    case 'video':   // 视频消息
                        break;
                    case 'shortVideo':  // 小视频消息
                        break;
                    case 'location':    // 地理位置消息
                        break;
                    case 'link':    // 链接消息
                        break;
                    default:
                        break;
                }
            }
        });
    }

    public function join(){
        $app = $this->application;
        $response = $app->server->serve();
        // 响应微信服务器
        $response->send();
        exit();
    }

}
